name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/*.md'

jobs:
  wiki_update:
    name: Update Wiki
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r scripts/update_wiki/requirements.txt
        pip install --upgrade pip

    - name: Update Wiki
      id: generated
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REPOSITORY: ${{ github.repository }}
      run: python3 scripts/update_wiki/main.py
